name: extract_macros

on:
  - workflow_dispatch
  - push

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Extract macros
        run: |
          pip install -U oletools && python _tools/extract_office_macros.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Extracted_Macros
          path: |
            **/*.xlsm
            **/*_Macros/*

      - name: Push to signed PR
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ github.token }}
          TARGET_BRANCH: "reviewed"
          UPDATE_COMMIT_MESSAGE: "Update from ${{ github.sha }} with extracted macro code"
        run: |
          git config --global user.email "commit@bot"
          git config --global user.name "Commit Bot"
          git branch -f "${TARGET_BRANCH}_pr"
          git checkout "${TARGET_BRANCH}_pr"
          rm -rf _tools/
          git add -A
          git commit -a -m "$UPDATE_COMMIT_MESSAGE" --allow-empty
          git push --set-upstream origin "${TARGET_BRANCH}_pr" --force
          gh pr edit "${TARGET_BRANCH}_pr" -b "$UPDATE_COMMIT_MESSAGE" || gh pr create --base $TARGET_BRANCH -t "Sign Macros" -b "$UPDATE_COMMIT_MESSAGE"
