name: sign

on:
  push:
    branches: ['reviewed']
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: upload-unsigned-artifact
      id: upload-unsigned-artifact
      uses: actions/upload-artifact@v4
      with:
        name: OfficeFiles
        path: OfficeFiles/*

    - name: Sign
      uses: signpath/github-action-submit-signing-request@v1
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 'a9adc20c-92e3-4345-805e-9df13b96dc87'
        project-slug: 'OfficeMacroGitTrackingDemo'
        signing-policy-slug: 'release-signing'
        github-artifact-id:  "${{steps.upload-unsigned-artifact.outputs.artifact-id}}"
        wait-for-completion: true
        output-artifact-directory: 'OfficeFiles.Signed'

    - name: upload-signed-artifact
      uses: actions/upload-artifact@v4
      with:
        name: OfficeFiles.Signed
        path: OfficeFiles.Signed/*
